name: Import Swagger to Postman

on:
  workflow_dispatch:
    inputs:
      next_latest_branch:
        description: 'The branch to checkout (e.g. release-5.8)'
        required: true

jobs:
  import-swagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.next_latest_branch }}

      - name: Install jq
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: Import Swagger Files to Postman
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
          POSTMAN_WORKSPACE: ${{ secrets.POSTMAN_WORKSPACE }}
        run: |
          # Define an array of swagger file names (adjust the path if necessary)
          files=(
            gateway-swagger.yml
            dashboard-swagger.yml
            mdcb-swagger.yml
            enterprise-developer-portal-swagger.yaml
            dashboard-admin-swagger.yml
          )
          
          for file in "${files[@]}"; do
            echo "Processing $file..."
            # Read and convert the file to a JSON string
            input=$(cat "tyk-docs/assets/others/$file" | jq -Rs '.')
          
            # Build the JSON payload with the expected structure
            payload="{\"type\": \"string\", \"input\": $input}"
          
            echo "Payload for $file:"
            echo "$payload"
          
            # Send the POST request to Postman's /import/openapi endpoint with the workspace query parameter
            curl --location --request POST "https://api.getpostman.com/import/openapi?workspace=${POSTMAN_WORKSPACE}" \
              --header "X-Api-Key: ${POSTMAN_API_KEY}" \
              --header "Content-Type: application/json" \
              --data-raw "$payload"
          
            echo "Done processing $file"
          done
